encryptionsalt: v1:Lcn1zt35+3k=:v1:AVFidY7zb4MSzMPN:pMx1/+ioYKfsssux7MdQfk0OsBMrRw==
  msinfraops-poc:tables:
    - name: msinfraops-poc-dev
      billingMode: PAY_PER_REQUEST
      hashKey: _pk
      rangeKey: _sk
      attributes:
        - name: _pk
          type: S
        - name: _sk
          type: S
        - name: attr1
          type: S
        - name: attr2
          type: S
        - name: attr3
          type: S
        - name: attr4
          type: N
      enableRecovery: false
      globalSecondaryIndex:
        - name: attr1-index
          hashKey: _sk
          rangeKey: attr1
          projectionType: ALL
          readCapacity: 0
          writeCapacity: 0
        - name: attr2-index
          hashKey: _sk
          rangeKey: attr2
          projectionType: ALL
          readCapacity: 0
          writeCapacity: 0
        - name: attr3-index
          hashKey: _sk
          rangeKey: attr3
          projectionType: ALL
          readCapacity: 0
          writeCapacity: 0
        - name: attr4-index
          hashKey: _sk
          rangeKey: attr4
          projectionType: ALL
          readCapacity: 0
          writeCapacity: 0
