#!/bin/env bash

cat <<EOF
window.TAXAMO_PUBLIC_KEY = "$TAXAMO_PUBLIC_KEY";
window.MS_API_SERVICES = "$MS_API_SERVICES";
window.GOOGLE_ANALYTICS_ID = "$GOOGLE_ANALYTICS_ID";
window.MS_GOOGLE_TAG_MANAGER_ID = "$MS_GOOGLE_TAG_MANAGER_ID";
window.MS_CDN_URL = "$MS_CDN_URL";
window.MS_UPLOADS_URL = "$MS_UPLOADS_URL";
window.MS_VWO_SMARTCODE_ACCOUNT_ID = "$MS_VWO_SMARTCODE_ACCOUNT_ID";
window.MS_APP_PATH = "$MS_APP_PATH";
window.MS_MOMIT_EVENT_QUESTION_NUMBER = ${MS_MOMIT_EVENT_QUESTION_NUMBER:-0};
window.MS_PACKAGE_UI = "$MS_PACKAGE_UI";
window.MS_SAVE_TAXAMO_RESPONSE = ${MS_SAVE_TAXAMO_RESPONSE:-true};
window.MS_MIRROR_REFLECTIONS_ENABLED = ${MS_MIRROR_REFLECTIONS_ENABLED:-false};
window.MS_INDICATOR_ENABLED = ${MS_INDICATOR_ENABLED:-false};
window.MS_BUILDER_ENABLED = ${MS_BUILDER_ENABLED:-false};
EOF
