#!/bin/env bash

cat <<EOF
window.MS_API_SERVICES = "$MS_API_SERVICES";
window.GOOGLE_ANALYTICS_ID = "$GOOGLE_ANALYTICS_ID";
window.MS_GOOGLE_TAG_MANAGER_ID = "$MS_GOOGLE_TAG_MANAGER_ID";
window.MS_VWO_SMARTCODE_ACCOUNT_ID = "$MS_VWO_SMARTCODE_ACCOUNT_ID";
window.MS_CDN_URL = "$MS_CDN_URL";
window.MS_UPLOADS_URL = "$MS_UPLOADS_URL";
window.MS_APP_PATH = "$MS_APP_PATH";
window.MS_MIRROR_REFLECTIONS_ENABLED = ${MS_MIRROR_REFLECTIONS_ENABLED:-false};
window.MS_INDICATOR_ENABLED = ${MS_INDICATOR_ENABLED:-false};
window.MS_BUILDER_ENABLED = ${MS_BUILDER_ENABLED:-false};
window.MS_AVAILABLE_COUNTRIES = ${MS_AVAILABLE_COUNTRIES:-[]};
EOF
