export const MWIQuestions: { [key: string]: string } = {
  'mws-1': 'I have a sense of belonging',
  'mws-2': 'I can talk openly about my values when we are making decisions',
  'mws-3': 'We talk about what matters to us',
  'mws-4': 'We support each other',
  'mws-5': 'We reassure each other',
  'mws-6': 'We enjoy working together',
  'mws-7': 'I feel I truly help our customers/clients',
  'mws-8': 'We contribute to products and services that enhance human well-being and/or the environment',
  'mws-9': 'What we do is worthwhile',
  'mws-10': 'We spend a lot of time on things that are truly important',
  'mws-11': 'I create and apply new ideas or concepts',
  'mws-12': 'I make a difference that matters to others',
  'mws-13': 'I experience a sense of achievement',
  'mws-14': 'I am excited by the available opportunities for me',
  'mws-15': 'At work my sense of what is right and wrong gets blurred',
  'mws-16': 'I don’t like who I am becoming at work',
  'mws-17': 'At work I feel divorced from myself',
  'mws-18': 'At work we face up to reality',
  'mws-19': 'We are tolerant of being human',
  'mws-20': 'We recognize that life is messy and that is OK',
  'mws-21': 'I feel inspired at work',
  'mws-22': 'The work we are doing makes me feel hopeful about the future',
  'mws-23': 'The vision we collectively work towards inspires me',
  'mws-24': 'I experience a sense of spiritual connection with my work',
  'mws-25': 'In this work I have the time and space to think',
  'mws-26': 'We have a good balance between focusing on getting things done and noticing how people are feeling',
  'mws-27': 'I create enough space for me',
  'mws-28': 'I have a good balance between the needs of others and my own needs',
  'mws-29': 'All things considered, I am satisfied with my life these days',
  'mws-30': 'All things considered, I have a sense of well-being these days',
  'mws-31': 'My stress level keeps me from appreciating the good things in life',
}
