service: "msinfraops-poc"

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  serverless-offline:
    port: 3200
    httpPort: 3005
  esbuild:
    exclude:
      - "@aws-sdk"

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - ".env.example"

provider:
  name: aws
  runtime: nodejs20.x

functions:
  poc-service:
    handler: src/functions/poc-service/index.handler
    events:
      - http:
          method: ANY
          path: "api/poc-service/{proxy+}"
          cors: true
  taxamo-webhook:
    handler: src/functions/taxamo-webhook/index.handler
