name: Detect Removed Sprint

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  id-token: write
  repository-projects: read
  issues: write
  contents: read

jobs:
  detect-state-removal:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v6

      - name: Assuming federated role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_FED_ROLE_ARN }}
          role-session-name: Federal

      - name: Install jq
        run: sudo apt update && sudo apt install -y jq

      - run: touch yesterday.txt

      - name: Copy Yesterday State File
        run: aws s3 cp s3://${{ secrets.BUCKET_NAME }}/yesterday.txt ./yesterday.txt

      - name: Run Sprint Script
        env:
          OWNER: ${{ github.repository_owner }}       
          REPO: ${{ github.repository }}              
          PROJECT_NUMBER: ${{ secrets.PROJECT_NUMBER }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPO_NAME="${REPO#*/}"
          chmod +x sprint-fetch.sh  
          ./sprint-fetch.sh

      - name: Save Todays State for Tomorrow
        run: |
          aws s3 cp ./yesterday.txt s3://${{ secrets.BUCKET_NAME }}/yesterday.txt
