name: Detect Removed Sprint

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  id-token: write
  repository-projects: read
  issues: write
  contents: read

jobs:
  detect-state-removal:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v6

      - name: Assuming federated role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_FED_ROLE_ARN }}
          role-session-name: Federal

      - name: Install jq
        run: sudo apt update && sudo apt install -y jq

      - run: touch yesterday.txt

      - name: Copy Yesterday State File
        run: aws s3 cp s3://${{ secrets.BUCKET_NAME }}/yesterday.txt ./yesterday.txt

      - name: Run Sprint Script
        env:
          PROJECT_NUMBER: 1
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          OWNER="${GITHUB_REPOSITORY_OWNER}"  
          REPO="${GITHUB_REPOSITORY}"     
          echo "REPO_NAME=${GITHUB_REPOSITORY#*/}"
          gh api graphql -f query='
            query($number: Int!) {
              viewer {
                projectV2(number: $number) {
                  title
                  items(first: 100) {
                    nodes {
                      content {
                        ... on Issue {
                          number
                          title
                        }
                        ... on PullRequest {
                          number
                          title
                        }
                      }
                      fieldValues(first: 20) {
                        nodes {
                          __typename

                          ... on ProjectV2ItemFieldTextValue {
                            text
                            field {
                              ... on ProjectV2FieldCommon {
                                name
                              }
                            }
                          }

                          ... on ProjectV2ItemFieldSingleSelectValue {
                            name
                            field {
                              ... on ProjectV2FieldCommon {
                                name
                              }
                            }
                          }

                          ... on ProjectV2ItemFieldIterationValue {
                            title
                            field {
                              ... on ProjectV2FieldCommon {
                                name
                              }
                            }
                          }

                          ... on ProjectV2ItemFieldNumberValue {
                            number
                            field {
                              ... on ProjectV2FieldCommon {
                                name
                              }
                            }
                          }

                          ... on ProjectV2ItemFieldDateValue {
                            date
                            field {
                              ... on ProjectV2FieldCommon {
                                name
                              }
                            }
                          }

                        }
                      }
                    }
                  }
                }
              }
            }
            '-F number=$PROJECT_NUMBER | jq .
      #       #  | jq -r '
      #       # .data.user.projectV2.items.nodes[] |
      #       #   .content.number as $num |
      #       #   (
      #       #     [.fieldValues.nodes[]
      #       #       | select(.field.name == "Sprint")
      #       #       | .name
      #       #     ][0] // "NO_SPRINT"
      #       #   ) as $sprint |
      #       #   "\($num),\($sprint)"
      #       # ' > today.txt

      # - name: Save Todays State for Tomorrow
      #   run: |
      #     aws s3 cp ./yesterday.txt s3://${{ secrets.BUCKET_NAME }}/yesterday.txt
